import { CdkTableModule } from '@angular/cdk/table';
import { NgModule } from '@angular/core';
import { MatAutocompleteModule, MatButtonModule, MatButtonToggleModule, MatCardModule, MatCheckboxModule, MatChipsModule, MatDatepickerModule, MatDialogModule, MatExpansionModule, MatFormFieldModule, MatGridListModule, MatIconModule, MatInputModule, MatListModule, MatMenuModule, MatNativeDateModule, MatOptionModule, MatPaginatorModule, MatProgressBarModule, MatProgressSpinnerModule, MatRadioModule, MatSelectModule, MatSidenavModule, MatSliderModule, MatSlideToggleModule, MatSnackBarModule, MatSortModule, MatStepperModule, MatTableModule, MatTabsModule, MatToolbarModule, MatTooltipModule } from '@angular/material';

@NgModule({
	imports: [
		MatToolbarModule,
		MatButtonModule,
		MatIconModule,
		MatCardModule,
		MatGridListModule,
		MatSnackBarModule,
		MatSidenavModule,
		MatListModule,
		MatChipsModule,
		MatFormFieldModule,
		MatSelectModule,
		MatOptionModule,
		MatInputModule,
		MatExpansionModule,
		MatAutocompleteModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		MatTabsModule,
		MatDialogModule,
		MatMenuModule,
		MatRadioModule,
		MatStepperModule,
		MatTooltipModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatButtonToggleModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatTableModule,
		MatPaginatorModule,
		CdkTableModule,
		MatSortModule,
		MatNativeDateModule
	],
	exports: [
		MatToolbarModule,
		MatButtonModule,
		MatIconModule,
		MatCardModule,
		MatGridListModule,
		MatSnackBarModule,
		MatSidenavModule,
		MatListModule,
		MatChipsModule,
		MatFormFieldModule,
		MatSelectModule,
		MatOptionModule,
		MatInputModule,
		MatExpansionModule,
		MatAutocompleteModule,
		MatProgressSpinnerModule,
		MatProgressBarModule,
		MatTabsModule,
		MatDialogModule,
		MatMenuModule,
		MatRadioModule,
		MatStepperModule,
		MatTooltipModule,
		MatCheckboxModule,
		MatDatepickerModule,
		MatButtonToggleModule,
		MatSliderModule,
		MatSlideToggleModule,
		MatTableModule,
		MatPaginatorModule,
		CdkTableModule,
		MatSortModule,
		MatNativeDateModule
	]
})
export class MaterialModule { }
